### ISSUE TITLE
MSRV is incorrectly stated, should be 1.87

### ISSUE THREAD

**Issue by nemosupremo** [webrtc-rs/webrtc#752]
I recently tried compiling a project using webrtc 0.14. The readme states the MSRV is 1.65, but the project failed to build with 1.85:

```
error[E0658]: use of unstable library feature `unsigned_is_multiple_of`
    --> /home/n/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sdp-0.10.0/src/description/session.rs:1155:22
     |
1155 |     if !fields.len().is_multiple_of(2) {
     |                      ^^^^^^^^^^^^^^
     |
     = note: see issue #128101 <https://github.com/rust-lang/rust/issues/128101> for more information
```

`is_multiple_of` was [stabilized in 1.87](https://doc.rust-lang.org/std/primitive.u32.html#method.is_multiple_of).
